apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-vko4
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-dcsv-tenant/rhtap-demo-app/hacbs-test-project-vko4@sha256:755fc28efd92180fcd5f736391559e9af7080df14a9b2310305508379f0f5ec9
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
