apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-vko4
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-vko4
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-vko4
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-vko4
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-vko4
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-dcsv-tenant/rhtap-demo-app/hacbs-test-project-vko4@sha256:755fc28efd92180fcd5f736391559e9af7080df14a9b2310305508379f0f5ec9
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
